---
title: "Practice"
author: "Jessie Lilly"
date: "March 1, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




## Generate a function that will generate, for a range of each of 'magnitude of B1', 'sample size', and 'error', a measure of the quality of the parameter estimate. 

## 1 A) Create a function that will generate random data with a parameter of 5.
```{r}
gen.mod <- function(n=50,b0=4,b1=5,sd.err=0.5){predictor<-runif(n)-50
response <- b0+b1*predictor+rnorm(n,mean=0,sd=sd.err)
return(data.frame(response=response,predictor=predictor))}
```

## Use the data from gen.mod to generate parameter estimates for 2 different B1

```{r}
n.times <- 1:1000
n <- c(10,15,20)
b1 <- c(2,3,4)
sd.err <- c(1,2,3)


est.df <- expand.grid(n.times=n.times,b1=b1,sd.err=sd.err)

for(i in 1:length(est.df$n.times))
{tmp.df<-gen.mod(n=est.df $ n[i], b0=4, b1=est.df$b1[i], est.df$sd.err[i])
est.lm <-lm(response ~ predictor,data=tmp.df)
est.df$param[i] <- summary(est.lm)$coefficients["predictor","t value"]
}

```

